USER_ROLE = 'user'
MODERATOR_ROLE = 'moderator'
ADMIN_ROLE = 'admin'

MAX_LENGTH_NAME = 150
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_ROLE = 15
MAX_LENGTH_SLUG = 50
MAX_LENGTH_GENRE_CATEGORY_NAME = 256
MAX_LENGTH_TITLE_NAME = 256
MAX_LENGTH_TITLE_DESCRIPTION = 256
